name: test

on:
  workflow_dispatch:
  

jobs:
  test-setup-v4:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup node@v4 
        uses: actions/setup-node@v4
        with:
          node-version: 18


  test-setup-v3:         
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
          - name: Checkout
            uses: actions/checkout@v3
      
          - name: Setup node@v3
            uses: actions/setup-node@v3
            with:
              node-version: 18
